const regionsInfo = 
{
	abruzzo: { name: "Abruzzo",people: 1311580},
	basilicata: { name: "Basilicata",people: 562869},
	bolzano: { name: "P.A. Bolzano",people: 531178},
	calabria: { name: "Calabria",people: 1947131},
	campania: { name: "Campania",people: 5801692},
	emilia_romagna: { name: "Emilia Romagna",people: 4459477 },
	friuli_venezia_giulia: { name: "Friuli Venezia Giulia",people: 1215220},
	lazio: { name: "Lazio",people: 5879082},
	liguria: { name: "Liguria",people: 1550640 },
	lombardia: { name: "Lombardia",people: 10060574},
	marche: { name: "Marche",people: 1525271},
	molise: { name: "Molise",people: 305617},
	piemonte: { name: "Piemonte",people: 4356406 },
	puglia: { name: "Puglia",people: 4029053},
	sardegna: { name: "Sardegna",people: 1639591},
	sicilia: { name: "Sicilia",people: 4999891},
	toscana: { name: "Toscana",people: 3729641},
	trento: { name: "P.A. Trento",people: 541098},
	umbria: { name: "Umbria",people: 882015},
	valle_aosta: { name: "Valle d'Aosta",people: 125666},
	veneto: { name: "Veneto",people: 4905854}
};

const variablesInfo =
{
	totale_casi: { name: "Totale Casi"},
	ricoverati_con_sintomi: { name: "Ricoverati Con Sintomi"},
	terapia_intensiva: { name: "Terapia Intensiva"},
	totale_ospedalizzati: { name: "Totale Ospedalizzati"},
	isolamento_domiciliare: { name: "Isolamento Domiciliare"},
	totale_attualmente_positivi: { name: "Totale Attualmente Positivi"},
	nuovi_attualmente_positivi: { name: "Nuovi Attualmente Positivi"},
	dimessi_guariti: { name: "Dimessi Guariti"},
	deceduti: { name: "Deceduti"},
	tamponi: { name: "Tamponi"},
	tamponi_su_popolazione : {name: "[%] Tamponi Su Popolazione"},
	totale_casi_su_tamponi: { name: "[%] Totale Casi Su Tamponi"},
	totale_casi_su_popolazione : {name: "[%] Totale Casi Su Popolazione"},
	deceduti_su_totale_casi: { name: "[%] Deceduti Su Totale Casi"},
	deceduti_su_popolazione: {name: "[%] Deceduti Su Popolazione"},
	dimessi_guariti_su_totale_casi: {name: "[%] Dimessi Guariti Su Totale Casi"},
	totale_ospedalizzati_su_popolazione: {name: "[%] Totale Ospedalizzati Su Popolazione"},
	terapia_intensiva_su_popolazione: {name: "[%] Terapia Intensiva Su Popolazione"},
	ricoverati_con_sintomi_su_popolazione: {name: "[%] Ricoverati Con Sintomi Su Popolazione"},
	isolamento_domiciliare_su_popolazione: {name: "[%] Isolamento Domiciliare Su Popolazione"},
	delta_totale_casi: {name: "Delta Totale Casi"},
	delta_totale_casi_su_popolazione: {name: "[%] Delta Totale Casi Su Popolazione"},
	delta_totale_ospedalizzati: {name: "Delta Totale Ospedalizzati"},
    delta_deceduti: {name: "Delta Deceduti"},
    delta_dimessi_guariti: {name: "Delta Dimessi Guariti"},
    delta_tamponi:{name: "Delta Tamponi"}
};